#!/usr/bin/env python3
"""Build the itch.io web version of Sisyphus.

Strategy: parse the original sisyphus_game.py with AST and produce a
web-ready module (sisyphus_web.py) that:
  1. Keeps every scene/flag/effect/ending logic byte-identical.
  2. Converts the 3 functions that call input() into async functions.
  3. Rewrites `input("> ")` call sites into `await input("> ")`.
  4. Drops the `if __name__ == "__main__"` block (JS drives play()).
  5. Prepends a small preamble that patches sys.stdout/sys.stderr to a
     JS terminal bridge and defines the async input() implementation.

The original file is never modified.
"""
import ast
import sys
from pathlib import Path

ASYNC_FUNCS = {"present_scene", "choose_final_path", "play"}


class Transform(ast.NodeTransformer):
    def visit_ImportFrom(self, node):
        # Drop the original `from __future__ import annotations` — the
        # preamble already declares it at the very top.
        if node.module == "__future__":
            return None
        return self.generic_visit(node)

    def visit_FunctionDef(self, node):
        if node.name in ASYNC_FUNCS:
            node = ast.copy_location(
                ast.AsyncFunctionDef(
                    name=node.name,
                    args=node.args,
                    body=node.body,
                    decorator_list=node.decorator_list,
                    returns=node.returns,
                    type_comment=node.type_comment,
                ),
                node,
            )
            ast.fix_missing_locations(node)
        return self.generic_visit(node)

    def visit_Call(self, node):
        # input(...) -> await input(...)
        if isinstance(node.func, ast.Name) and node.func.id == "input":
            aw = ast.Await(value=node)
            return ast.copy_location(aw, node)
        # async game functions must be awaited at call sites (e.g. play() ->
        # await present_scene(...), await choose_final_path(...))
        if isinstance(node.func, ast.Name) and node.func.id in ASYNC_FUNCS:
            aw = ast.Await(value=node)
            return ast.copy_location(aw, node)
        return self.generic_visit(node)

    def visit_If(self, node):
        # Drop `if __name__ == "__main__": play()`
        test = node.test
        if (
            isinstance(test, ast.Compare)
            and isinstance(test.left, ast.Name)
            and test.left.id == "__name__"
            and len(test.ops) == 1
            and isinstance(test.ops[0], ast.Eq)
            and len(test.comparators) == 1
            and isinstance(test.comparators[0], ast.Constant)
            and test.comparators[0].value == "__main__"
        ):
            return None
        return self.generic_visit(node)


PREAMBLE = '''\
# ============================================================
# Web bridge preamble (generated by build.py - never edit by hand)
# ============================================================
from __future__ import annotations
import asyncio
import builtins
import js as _js
import sys

class _TermOut:
    """Route Python print() output to the xterm.js terminal."""
    def write(self, s):
        _js.termWrite(s)
    def flush(self):
        pass

sys.stdout = _TermOut()
sys.stderr = _TermOut()

_pending_input = None

async def input(prompt="> "):
    """Async stand-in for builtins.input. Resumed by JS via resolveInput()."""
    global _pending_input
    _js.termWrite(prompt)
    _js.notifyInputStart()
    _pending_input = asyncio.get_running_loop().create_future()
    return await _pending_input

def resolveInput(text):
    global _pending_input
    if _pending_input is not None:
        fut = _pending_input
        _pending_input = None
        if not fut.done():
            fut.set_result(text)

builtins.input = input

# ============================================================
# Original game code follows (AST-transformed, logic unchanged)
# ============================================================
'''


def main() -> None:
    # Default source: sibling of the web/ dir, i.e. repo root sisyphus_game.py.
    default_src = str(Path(__file__).resolve().parent.parent / "sisyphus_game.py")
    src_path = Path(sys.argv[1] if len(sys.argv) > 1 else default_src)
    out_path = Path(sys.argv[2] if len(sys.argv) > 2 else "sisyphus_web.py")

    source = src_path.read_text(encoding="utf-8")
    tree = ast.parse(source)
    tree = Transform().visit(tree)
    ast.fix_missing_locations(tree)
    body = ast.unparse(tree)

    out_path.write_text(PREAMBLE + body + "\n", encoding="utf-8")
    print(f"wrote {out_path} ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
